import argv from './argv'
import backup from './backup'
import clean from './clean'
import compile from './compile'
import copy from './copy'
import download from './download'
import exec from './exec'
import formatArgument from './formatArgument'
import getBasename from './getBasename'
import getDirname from './getDirname'
import getExtname from './getExtname'
import getFilename from './getFilename'
import getName from './getName'
import home from './home'
import i from './i'
import info from './info'
import isExisted from './isExisted'
import isSame from './isSame'
import link from './link'
import mkdir from './mkdir'
import move from './move'
import normalizePath from './normalizePath'
import normalizePathToArray from './normalizePathToArray'
import os from './os'
import parseJson from './parseJson'
import parseString from './parseString'
import prompt from './prompt'
import read from './read'
import recover from './recover'
import remove from './remove'
import rename from './rename'
import root from './root'
import say from './say'
import sleep from './sleep'
import source from './source'
import stat from './stat'
import type from './type'
import watch from './watch'
import wrapList from './wrapList'
import write from './write'
import zip from './zip'
const $ = {
  argv, backup, clean, compile, copy, download, exec, formatArgument, getBasename, getDirname, getExtname, getFilename, getName, home, i, info, isExisted, isSame, link, mkdir, move, normalizePath, normalizePathToArray, os, parseJson, parseString, prompt, read, recover, remove, rename, root, say, sleep, source, stat, type, watch, wrapList, write, zip,
}
export default $

// ---