import argv from './argv'
import backup from './backup'
import clean from './clean'
import copy from './copy'
import download from './download'
import exec from './exec'
import getBasename from './getBasename'
import getDirname from './getDirname'
import getExtname from './getExtname'
import getFilename from './getFilename'
import getName from './getName'
import getType from './getType'
import glob from './glob'
import home from './home'
import isAsyncFunction from './isAsyncFunction'
import isExisted from './isExisted'
import isFunction from './isFunction'
import isSame from './isSame'
import link from './link'
import log from './log'
import mkdir from './mkdir'
import move from './move'
import normalizePath from './normalizePath'
import os from './os'
import prompt from './prompt'
import read from './read'
import recover from './recover'
import remove from './remove'
import rename from './rename'
import root from './root'
import say from './say'
import sleep from './sleep'
import stat from './stat'
import toArray from './toArray'
import toDate from './toDate'
import toJson from './toJson'
import toString from './toString'
import watch from './watch'
import wrapList from './wrapList'
import write from './write'
import zip from './zip'
const $ = {
  argv, backup, clean, copy, download, exec, getBasename, getDirname, getExtname, getFilename, getName, getType, glob, home, isAsyncFunction, isExisted, isFunction, isSame, link, log, mkdir, move, normalizePath, os, prompt, read, recover, remove, rename, root, say, sleep, stat, toArray, toDate, toJson, toString, watch, wrapList, write, zip,
}
export default $

// ---
